# SecretStore - AWS Secrets Manager
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ${{ values.teamName }}-aws-secrets
  namespace: team-${{ values.teamName }}
  labels:
    fasti.sh/team: ${{ values.teamName }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: ${{ values.teamName }}-workload

---
# SecretStore - AWS Parameter Store
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: ${{ values.teamName }}-aws-params
  namespace: team-${{ values.teamName }}
  labels:
    fasti.sh/team: ${{ values.teamName }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: ${AWS_REGION}
      auth:
        jwt:
          serviceAccountRef:
            name: ${{ values.teamName }}-workload
