apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: ${{ values.teamName }}-default
  namespace: team-${{ values.teamName }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow from same namespace
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: team-${{ values.teamName }}
    # Allow from ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
    # Allow from observability (Grafana, Prometheus)
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
  egress:
    # Allow DNS
    - to:
        - namespaceSelector: {}
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow same namespace
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: team-${{ values.teamName }}
    # Allow external (not internal cluster)
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            except:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
