apiVersion: v1
kind: ServiceAccount
metadata:
  name: ${{ values.teamName }}-workload
  namespace: team-${{ values.teamName }}
  labels:
    fasti.sh/team: ${{ values.teamName }}
{%- if values.enableAwsAccess %}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/team-${{ values.teamName }}-workload
{%- endif %}
